mealplanner_dbt:
  outputs:
    dev:
      type: duckdb
      # Navigate to groceries.duckdb that is one directory up
      path: ../src/mealplanner/backend/data/groceries.duckdb   # data folder inside project package
      threads: 1

    # Not decided yet but perhaps snowflake?
    prod:
      type: snowflake
      path: prod.snowflake 
      threads: 4

  target: dev