version: 2
sources:
  - name: livsmedelsverket
    schema: raw
    tables:
      - name: raw_grocery
        description: "Food item master from Livsmedelsverket API."
      - name: raw_nutrient
        description: "Nutrient values for a food item."
      - name: raw_classification
        description: "Classification categories for a food item."
      - name: raw_ingredient
        description: "Ingredient composition for a food item (label-level)."
      - name: raw_component
        description: "Underlying raw materials/components used for nutrient calculations."